import 'package:flutter/material.dart';

import '../../../core/constants/app_colors.dart';

/// One emitted wave of the Symphonie Collective.
///
/// Born from a tap: [offsetX]/[offsetY] are normalized screen
/// coordinates (the tap position), [noteIndex] indexes the 20-note
/// C-major pentatonic scale (bottom of the screen = heavy/melancholy,
/// top = crystalline/hope), [hueIndex] indexes the four allowed hues
/// (X bands — ROSE is destruction-only and can never appear here).
class KenosWave {
  KenosWave({
    required this.id,
    required this.offsetX,
    required this.offsetY,
    required this.noteIndex,
    required this.hueIndex,
    required this.bornAt,
  });

  final String id;
  final double offsetX;
  final double offsetY;

  /// 0..19 into the pentatonic scale (0 = lowest C2).
  final int noteIndex;

  /// 0..3 into [WavePalette.hues] (left = purple, right = cyan).
  final int hueIndex;

  final DateTime bornAt;

  /// Sound envelope: 6 s (baked in the asset). The visual breathes a
  /// little longer to fade out.
  static const Duration soundLife = Duration(seconds: 6);
  static const Duration visualLife = Duration(seconds: 7);

  /// 0..1 progress of the visual life.
  double progressAt(DateTime now) =>
      (now.difference(bornAt).inMicroseconds / visualLife.inMicroseconds)
          .clamp(0.0, 1.0);

  bool isExpiredAt(DateTime now) =>
      now.difference(bornAt) >= visualLife;
}

/// The four wave hues — Cosmic Zen bands only. ROSE is reserved for
/// destruction and is deliberately absent from this palette.
class WavePalette {
  WavePalette._();

  static const List<Color> hues = [
    AppColors.purple, // left  — mystery
    AppColors.indigo, //       — the ether
    AppColors.teal,   //       — calm
    AppColors.cyan,   // right — clarity
  ];

  static Color hueFor(int index) => hues[index.clamp(0, hues.length - 1)];
}

/// Pure mapping math, shared by the screen and the tests.
class WaveMath {
  WaveMath._();

  static const int noteCount = 20;
  // Literal 4: WavePalette.hues.length is not a const expression.
  static const int hueCount = 4;

  /// Y → note: bottom of the screen = low (melancholy), top = high
  /// (hope) — exactly the submitted POC's inverse mapping.
  static int noteForY(double normalizedY) {
    final i = ((1 - normalizedY) * noteCount).floor();
    return i.clamp(0, noteCount - 1);
  }

  /// X → hue band.
  static int hueForX(double normalizedX) {
    final i = (normalizedX * hueCount).floor();
    return i.clamp(0, hueCount - 1);
  }

  /// Asset of a note (generated by tool/gen_audio.py).
  static String assetForNote(int noteIndex) =>
      'assets/audio/waves/wave_${noteIndex.toString().padLeft(2, '0')}.wav';
}
